import fs from 'fs';
import gulp from 'gulp';
import theo from 'theo';
import sassVar from '../util/sassvar';
import getGulpTask from '../util/getgulptask';
import { javascriptConst } from '../util/constantcase';

const motionTokensPath = 'packages/seeds-motion/tokens.yml';

function getGulpMotionTask(transform, format, opts = {}) {
  return getGulpTask('seeds-motion', transform, format, opts);
}

gulp.task('motion-scss', getGulpMotionTask('web', 'scss'));
gulp.task('motion-js', getGulpMotionTask('js', 'common.js'));

gulp.task('motion-docs', () => {
  theo.plugins
    .file(motionTokensPath)
    .pipe(theo.plugins.transform('web'))
    .pipe(theo.plugins.getResult((result) => {
      const tokens = JSON.parse(result);
      const easings = tokens.propKeys.map((key) => {
        const prop = tokens.props[key];
        const { value, description } = prop;

        return {
          sass: sassVar(prop.package, prop.name),
          javascript: javascriptConst(prop.package, prop.name),
          value,
          description
        }
      });

      fs.writeFileSync('docs/_includes/motion.html', `<!-- GENERATED BY GULP - DO NOT EDIT -->\n\n<script>window.seedsMotion = ${JSON.stringify(easings)};</script>`);
    })
  );
});

gulp.task('motion', [
  'motion-scss',
  'motion-js',
  'motion-docs'
]);