import fs from 'fs';
import gulp from 'gulp';
import theo from 'theo';
import sassVar from '../util/sassvar';
import getGulpTask from '../util/getgulptask';
import { javascriptConst } from '../util/constantcase';

const spaceTokensPath = 'packages/seeds-space/tokens.yml';

function getGulpSpaceTask(transform, format, opts = {}) {
  return getGulpTask('seeds-space', transform, format, opts);
}

gulp.task('space-scss', getGulpSpaceTask('web', 'scss'));
gulp.task('space-js', getGulpSpaceTask('js', 'common.js'));

gulp.task('space-docs', () => {
  theo.plugins
    .file(spaceTokensPath)
    .pipe(theo.plugins.transform('web'))
    .pipe(theo.plugins.getResult((result) => {
      const tokens = JSON.parse(result);
      const size = tokens.propKeys.map((key) => {
        const prop = tokens.props[key];
        const { value, description } = prop;

        return {
          sass: sassVar(prop.package, prop.name),
          javascript: javascriptConst(prop.package, prop.name),
          value,
          description
        }
      });

      fs.writeFileSync('docs/_includes/space.html', `<!-- GENERATED BY GULP - DO NOT EDIT -->\n\n<script>window.seedsSpace = ${JSON.stringify(size)};</script>`);
    })
  );
});

gulp.task('space', [
    'space-scss',
    'space-js',
    'space-docs'
]);
