const fs = require('fs');
const del = require('del');
const gulp = require('gulp');
const theo = require('theo');
const sassVar = require('@sproutsocial/seeds-utils/sassvar').sassVar;
const getGulpTask = require('@sproutsocial/seeds-utils/getgulptask');
const javascriptConst = require('@sproutsocial/seeds-utils/constantcase').javascriptConst;
const makeDir = require('make-dir');

const borderTokensPath = './tokens.yml';
require('@sproutsocial/seeds-utils/theo');

function getGulpBorderTask(transform, format, opts = {}) {
  return getGulpTask('seeds-border', transform, format, opts);
}

gulp.task('clean', () => {
  return del(['border/_generated/*']);
});

gulp.task('border-scss', getGulpBorderTask('web', 'scss'));
gulp.task('border-js', getGulpBorderTask('js', 'common.js'));

gulp.task('border-docs', done => {
  theo.plugins.file(borderTokensPath).pipe(theo.plugins.transform('web')).pipe(
    theo.plugins.getResult(result => {
      const tokens = JSON.parse(result);
      const easings = tokens.propKeys.map(key => {
        const prop = tokens.props[key];
        const {value, description} = prop;

        return {
          sass: sassVar(prop.package, prop.name),
          javascript: javascriptConst(prop.package, prop.name),
          value,
          description
        };
      });

      makeDir('border/_generated/').then(() => {
        fs.writeFileSync(
          'border/_generated/border.html',
          `<!-- GENERATED BY GULP - DO NOT EDIT -->\n\n<script>window.seedsBorder = ${JSON.stringify(
            easings
          )};</script>`
        );
        done();
      });
    })
  );
});

gulp.task('default', gulp.series(['clean', gulp.parallel(['border-scss', 'border-js']), 'border-docs']));
