const fs = require('fs');
const del = require('del');
const gulp = require('gulp');
const theo = require('theo');
const insert = require('gulp-insert');
const rename = require('gulp-rename');
const upperFirst = require('lodash.upperfirst');
const sassVar = require('@sproutsocial/seeds-utils/sassvar').sassVar;
const suitCssName = require('@sproutsocial/seeds-utils/sassvar').suitCssName;
const javascriptConst = require('@sproutsocial/seeds-utils/constantcase').javascriptConst;
const makeDir = require('make-dir');

const getGulpTask = require('@sproutsocial/seeds-utils/getgulptask');

const typographyTokensPath = './tokens.yml';

require('@sproutsocial/seeds-utils/theo');

gulp.task('clean', () => {
  return del(['typography/_generated/*']);
});

const typographyFunction = `$Typography-unit: px !default;
$Typography-size--base: $Typography-size--400 !default;
@function Typography-getunit($size) {
  @if $Typography-unit == "rem" {
    $remSize: $size / $Typography-size--base;
    @return #{$remSize}rem;
  }
  @else {
    @return $size;
  }
}
`;

function getGulpTypographyTask(transform, format, opts = {}) {
  return getGulpTask('seeds-typography', transform, format, opts);
}

gulp.task('typography-scss', getGulpTypographyTask('web', 'scss', {appendFile: typographyFunction}));
gulp.task('typography-js', getGulpTypographyTask('js', 'common.js'));
gulp.task(
  'typography-sketch',
  getGulpTypographyTask('sketch', 'sketchtext.json', {
    dest: 'typography/_generated',
    appendVersion: true
  })
);

gulp.task('typography-docs', done => {
  theo.plugins.file(typographyTokensPath).pipe(theo.plugins.transform('web')).pipe(
    theo.plugins.getResult(result => {
      const tokens = JSON.parse(result);
      const tokensJson = tokens.propKeys.map(key => {
        const prop = tokens.props[key];
        return {
          value: prop.value.value || prop.value,
          app: upperFirst(prop.name),
          sass: `@include ${suitCssName(prop.package, prop.name)};`,
          javascript: `{ style: ${javascriptConst(prop.package, prop.name)} }`,
          lineHeightProportional: prop.value.rules && prop.value.rules['line-height'],
          lineHeightPx: prop.value.rules && prop.value.rules['line-height'] * parseInt(prop.value.value, 10),
          category: prop.category
        };
      });

      makeDir('typography/_generated/').then(() => {
        fs.writeFileSync(
          'typography/_generated/typography.html',
          `<!-- GENERATED BY GULP - DO NOT EDIT -->\n\n<script>window.seedsTypography = ${JSON.stringify(
            tokensJson
          )};</script>`
        );
        done();
      });
    })
  );
});

gulp.task(
  'default',
  gulp.series(['clean', gulp.parallel(['typography-scss', 'typography-js', 'typography-sketch']), 'typography-docs'])
);
