const fs = require('fs');
const del = require('del');
const gulp = require('gulp');
const theo = require('theo');
const insert = require('gulp-insert');
const rename = require('gulp-rename');
const upperFirst = require('lodash.upperfirst');
const sassVar = require('../seeds-util/sassvar').sassVar;
const suitCssName = require('../seeds-util/sassvar').suitCssName;
const javascriptConst = require('../seeds-util/constantcase').javascriptConst;
const makeDir = require('make-dir');

const getGulpTask = require('../seeds-util/getgulptask');

const typographyTokensPath = './tokens.yml';

require('../seeds-util/theo');

gulp.task('clean', () => {
  return del(['docs/downloads/*']);
});

const typographyFunction = `$Typography-unit: px !default;
$Typography-size--base: $Typography-size--400 !default;
@function Typography-getunit($size) {
  @if $Typography-unit == "rem" {
    $remSize: $size / $Typography-size--base;
    @return #{$remSize}rem;
  }
  @else {
    @return $size;
  }
}
`;

function getGulpTypographyTask(transform, format, opts = {}) {
  return getGulpTask('seeds-typography', transform, format, opts);
}

gulp.task(
  'typography-scss',
  getGulpTypographyTask('web', 'scss', {appendFile: typographyFunction})
);
gulp.task('typography-js', getGulpTypographyTask('js', 'common.js'));
gulp.task(
  'typography-sketch',
  getGulpTypographyTask('sketch', 'sketchtext.json', {
    dest: 'docs/downloads',
    appendVersion: true
  })
);

gulp.task('typography-docs', done => {
  theo.plugins.file(typographyTokensPath).pipe(theo.plugins.transform('web')).pipe(
    theo.plugins.getResult(result => {
      const tokens = JSON.parse(result);
      const sizeProps = tokens.propKeys.filter(key => tokens.props[key].type === 'font size');
      const sizes = sizeProps.map(key => {
        const prop = tokens.props[key];
        return {
          size: prop.value.value,
          app: upperFirst(prop.name),
          sass: `@include ${suitCssName(prop.package, prop.name)};`,
          javascript: `{ style: ${javascriptConst(prop.package, prop.name)} }`,
          lineHeightProportional: prop.value.rules['line-height'],
          lineHeightPx: prop.value.rules['line-height'] * parseInt(prop.value.value, 10)
        };
      });

      makeDir('docs/_includes/').then(() => {
        fs.writeFileSync(
          'docs/_includes/typography.html',
          `<!-- GENERATED BY GULP - DO NOT EDIT -->\n\n<script>window.seedsTypography = ${JSON.stringify(
            sizes
          )};</script>`
        );
        done();
      });
    })
  );
});

gulp.task(
  'default',
  gulp.series([
    'clean',
    gulp.parallel(['typography-scss', 'typography-js', 'typography-sketch']),
    'typography-docs'
  ])
);
