const fs = require('fs');
const del = require('del');
const exec = require('child_process').exec;
const gulp = require('gulp');
const theo = require('theo');
const pascalCase = require('pascal-case');
const camelCase = require('lodash.camelcase');
const snakeCase = require('lodash.snakecase');
const upperFirst = require('lodash.upperfirst');
const tinycolor = require('tinycolor2');
const ase = require('ase-utils');
const makeDir = require('make-dir');

const versions = require('../seeds-util/versions');
const sassVar = require('../seeds-util/sassvar').sassVar;
const getGulpTask = require('../seeds-util/getgulptask');
const constantCase = require('../seeds-util/constantcase').constantCase;
const javascriptConst = require('../seeds-util/constantcase').javascriptConst;
const getPercentageRGB = require('../seeds-util/getpercentagergb');

const networkColorTokensPath = './tokens.yml';
require('../seeds-util/theo');

// TODO: Consider eliminating a lot of the duplication in this file

function getGulpNetworkColorTask(transform, format, opts = {}) {
  return getGulpTask('seeds-networkcolor', transform, format, opts);
}

gulp.task('clean', () => {
  return del(['docs/downloads/*']);
});

gulp.task('networkcolor-scss', getGulpNetworkColorTask('web', 'scss'));

gulp.task('networkcolor-js', getGulpNetworkColorTask('js', 'common.js'));

gulp.task(
  'networkcolor-swift',
  getGulpNetworkColorTask('swift', 'swift', {
    filename: `UIColor+${pascalCase('seeds-networkcolor')}`,
    dest: 'docs/downloads',
    prependFile: `// seeds-networkcolor\n// version ${versions['seeds-networkcolor']}`
  })
);

gulp.task(
  'networkcolor-android',
  getGulpNetworkColorTask('android', 'android.xml', {
    filename: snakeCase('seeds-networkcolor'),
    dest: 'docs/downloads'
  })
);

gulp.task(
  'networkcolor-python',
  getGulpNetworkColorTask('web', 'python.py', {
    filename: snakeCase('seeds-networkcolor'),
    dest: 'docs/downloads',
    prependFile: `# seeds-networkcolor\n# version ${versions['seeds-networkcolor']}`
  })
);

gulp.task(
  'networkcolor-sketch',
  getGulpNetworkColorTask('sketch', 'sketch.sketchpalette', {
    appendVersion: true,
    dest: 'docs/downloads'
  })
);

gulp.task('networkcolor-ase', done => {
  return gulp
    .src(networkColorTokensPath)
    .pipe(theo.plugins.transform('designapp'))
    .pipe(theo.plugins.format('ase'))
    .pipe(
      theo.plugins.getResult(result => {
        const wstream = fs.createWriteStream(`docs/downloads/seeds-networkcolor.${versions['seeds-networkcolor']}.ase`);
        wstream.write(ase.encode(JSON.parse(result)));
        wstream.end();
        done();
      })
    );
});

gulp.task(
  'networkcolor-clr',
  gulp.series([
    'networkcolor-ase',
    cb => {
      const downloadDir = `${process.cwd()}/docs/downloads`;
      exec(
        `${process.cwd()}/node_modules/ase-util/bin/ase2clr ${downloadDir}/seeds-networkcolor.${versions[
          'seeds-networkcolor'
        ]}.ase ${downloadDir}/seeds-networkcolor.${versions['seeds-networkcolor']}.clr`,
        err => {
          cb(err);
        }
      );
    }
  ])
);

gulp.task('networkcolor-docs', done => {
  theo.plugins.file(networkColorTokensPath).pipe(theo.plugins.transform('web')).pipe(
    theo.plugins.getResult(result => {
      const tokens = JSON.parse(result);
      const colors = tokens.propKeys.map(key => {
        const prop = tokens.props[key];
        const {category, value} = prop;

        return {
          category,
          value,
          palette: upperFirst(prop.name),
          sass: sassVar(prop.package, prop.name),
          javascript: javascriptConst(prop.package, prop.name),
          swift: `UIColor().${camelCase(prop.name)}()`,
          android: constantCase(prop.name),
          python: camelCase(prop.name),
          rgb: tinycolor(value).toRgbString(value)
        };
      });

      makeDir('docs/_includes/').then(() => {
        fs.writeFileSync(
          'docs/_includes/networkcolors.html',
          `<!-- GENERATED BY GULP - DO NOT EDIT -->\n\n<script>window.seedsColors = ${JSON.stringify(colors)};</script>`
        );
        done();
      });
    })
  );
});

gulp.task(
  'default',
  gulp.series([
    'clean',
    gulp.parallel([
      'networkcolor-scss',
      'networkcolor-js',
      'networkcolor-swift',
      'networkcolor-android',
      'networkcolor-python',
      'networkcolor-sketch',
      'networkcolor-clr'
    ]),
    'networkcolor-docs'
  ])
);
